[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "xstac"
author = "Tom Augspurger"
author-email = "taugspurger@microsoft.com"
classifiers = [ "License :: OSI Approved :: MIT License",]
requires = [
    "xarray",
    "numpy",
    "pystac",
    "pandas",
    "pyproj",
    # these are just for generate
    "fsspec",
    "adlfs",
]


