[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "xstac"
authors = [
    {name = "Tom Augspurger", email = "taugspurger@microsoft.com"},
]
dependencies = [
    "xarray",
    "numpy",
    "pystac>=1.0.0b3",
    "pandas",
    "pyproj",
    "pydantic",
    "zarr",
    "dask[array]",  # for chunking
    # these are just for generate
    "fsspec",
    "adlfs",
]
classifiers = ["License :: OSI Approved :: MIT License",]
dynamic = ['version', 'description']
